import {
  materialize,
  resolveTheme,
  ScreenState,
  type TerminalTimeline,
  type Theme,
  type WindowStyle,
} from '@typeframe/core/lite'

export interface RenderOptions {
  title?: string
  /** px per column (default 8) */
  charWidth?: number
  /** px per row (default 18) */
  lineHeight?: number
  /** inner padding in px (default 16) */
  padding?: number
  /** default pause after an output event without an explicit delay (default 30ms) */
  outputDelayMs?: number
}

const BAR_H = 34
const FONT_STACK = "ui-monospace,SFMono-Regular,Menlo,Consolas,'Liberation Mono',monospace"

const XML_ENT: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&apos;',
}

/** XML-escape all user-controlled text before it enters an SVG. */
export function escapeXml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => XML_ENT[c] as string)
}

/** Format ms as minimal deterministic seconds ("650" -> "0.65", "0" -> "0"). */
function fmt(ms: number): string {
  const s = (ms / 1000).toFixed(3)
  return s.replace(/(\.\d*?)0+$/, '$1').replace(/\.$/, '')
}

/**
 * Render a timeline to a self-contained animated SVG (zero runtime JS).
 * Deterministic: same timeline + theme + seed -> byte-identical output.
 */
export function renderSVG(timeline: TerminalTimeline, opts: RenderOptions = {}): string {
  const cw = opts.charWidth ?? 8
  const lh = opts.lineHeight ?? 18
  const pad = opts.padding ?? 16
  const theme = resolveTheme(timeline.meta.theme)
  const { width: cols, height: rows } = timeline.meta.dimensions
  const chrome = timeline.meta.windowStyle
  const barH = chrome === 'macos' || chrome === 'flat' ? BAR_H : 0
  const svgW = pad * 2 + cols * cw
  const svgH = barH + pad * 2 + rows * lh
  const top = barH + pad
  const title = opts.title ?? timeline.meta.title ?? 'terminal session'

  interface Screen {
    start: number
    end: number | null
    state: ScreenState
  }
  const screens: Screen[] = []
  let state = new ScreenState(cols, rows)
  let screenStart = 0
  let t = 0

  for (const ev of materialize(timeline)) {
    switch (ev.type) {
      case 'wait':
        t += ev.duration
        break
      case 'type': {
        const per = (ev.delay ?? 60) / Math.max(1, [...ev.text].length)
        for (const ch of ev.text) {
          t += per
          if (ch === '\n') state.newline()
          else state.put(ch, t, 'typed')
        }
        break
      }
      case 'output':
        t += ev.delay ?? opts.outputDelayMs ?? 30
        state.apply(ev, t, { stderrColor: theme.palette.red })
        break
      case 'clear':
        screens.push({ start: screenStart, end: t, state })
        state = new ScreenState(cols, rows)
        screenStart = t
        break
      default:
        state.apply(ev, t)
        break
    }
  }
  screens.push({ start: screenStart, end: null, state })

  return assembleSVG({
    screens,
    chrome,
    theme,
    svgW,
    svgH,
    pad,
    cw,
    lh,
    top,
    title,
    endTime: t,
    cols,
    rows,
  })
}

interface AssembleArgs {
  screens: { start: number; end: number | null; state: ScreenState }[]
  chrome: WindowStyle
  theme: Theme
  svgW: number
  svgH: number
  pad: number
  cw: number
  lh: number
  top: number
  title: string
  endTime: number
  cols: number
  rows: number
}

function assembleSVG(a: AssembleArgs): string {
  const { screens, chrome, theme, svgW, svgH, pad, cw, lh, top, title, endTime, cols, rows } = a
  const parts: string[] = []
  parts.push('<!-- generated by typeframe -->')
  parts.push(
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${svgW} ${svgH}" width="${svgW}" height="${svgH}" role="img" aria-label="${escapeXml(title)}">`,
  )
  parts.push(
    `<style>text{font-family:${FONT_STACK};font-size:14px;white-space:pre}` +
      `.tf-k{opacity:0;animation:tf-in 1ms linear var(--d,0s) both}` +
      `.tf-cursor{opacity:0;animation:tf-in 1ms linear var(--d,0s) both,tf-blink 1.1s steps(1) infinite}` +
      `@keyframes tf-in{from{opacity:0}to{opacity:1}}` +
      `@keyframes tf-show{from{opacity:0}to{opacity:1}}` +
      `@keyframes tf-hide{from{opacity:1}to{opacity:0}}` +
      `@keyframes tf-blink{50%{opacity:.15}}` +
      `@media (prefers-reduced-motion:reduce){.tf-k,.tf-cursor{opacity:1;animation:none}.tf-screen{animation:none}.tf-screen:not(.tf-live){display:none}}` +
      `</style>`,
  )
  parts.push(
    `<rect x="0" y="0" width="${svgW}" height="${svgH}" rx="${chrome === 'macos' ? 12 : 0}" fill="${theme.bg}"/>`,
  )
  parts.push(renderChrome(chrome, svgW, svgH, title, theme))

  screens.forEach((s, i) => {
    const live = i === screens.length - 1
    const anim =
      s.end === null
        ? 'animation:tf-show 1ms linear var(--s) both'
        : 'animation:tf-show 1ms linear var(--s) both,tf-hide 1ms linear var(--e) forwards'
    const vars = s.end === null ? `--s:${fmt(s.start)}` : `--s:${fmt(s.start)};--e:${fmt(s.end)}`
    parts.push(`<g class="tf-screen${live ? ' tf-live' : ''}" style="${anim};${vars}">`)
    for (const { row, col, cell } of s.state.cells()) {
      const attrs: string[] = ['class="tf-k"', `style="--d:${fmt(cell.stamp)}"`]
      if (cell.color) attrs.push(`fill="${cell.color}"`)
      if (cell.bold) attrs.push('font-weight="700"')
      if (cell.italic) attrs.push('font-style="italic"')
      if (cell.underline) attrs.push('text-decoration="underline"')
      parts.push(
        `<text x="${pad + col * cw}" y="${top + row * lh + lh - 5}" ${attrs.join(' ')}>${escapeXml(cell.ch)}</text>`,
      )
    }
    if (live && s.state.cursorVisible) {
      const x = pad + Math.min(s.state.cursorCol, cols - 1) * cw
      const y = top + Math.min(s.state.cursorRow, rows - 1) * lh + 3
      parts.push(
        `<rect class="tf-cursor" x="${x}" y="${y}" width="${cw - 2}" height="${lh - 6}" fill="${theme.cursor}" style="--d:${fmt(endTime)}"/>`,
      )
    }
    parts.push('</g>')
  })
  parts.push('</svg>')
  return parts.join('\n')
}

function renderChrome(
  chrome: WindowStyle,
  w: number,
  h: number,
  title: string,
  theme: Theme,
): string {
  switch (chrome) {
    case 'macos':
      return (
        `<rect x="0.5" y="0.5" width="${w - 1}" height="${h - 1}" rx="12" fill="none" stroke="${theme.fg}" stroke-opacity="0.2"/>` +
        `<circle cx="20" cy="17" r="6" fill="#ff5f57"/><circle cx="40" cy="17" r="6" fill="#febc2e"/><circle cx="60" cy="17" r="6" fill="#28c840"/>`
      )
    case 'flat':
      return (
        `<rect x="0" y="0" width="${w}" height="${BAR_H}" fill="${theme.fg}" opacity="0.08"/>` +
        `<text x="${w / 2}" y="21" text-anchor="middle" fill="${theme.fg}" fill-opacity="0.7" style="font-size:12px">${escapeXml(title)}</text>`
      )
    case 'minimal':
      return `<rect x="0.5" y="0.5" width="${w - 1}" height="${h - 1}" fill="none" stroke="${theme.fg}" stroke-opacity="0.35"/>`
    case 'none':
      return ''
  }
}
