import { parseTimeline } from '@typeframe/core'
import { describe, expect, it } from 'vitest'
import { renderSVG } from '../src/render.js'

const hero = parseTimeline({
  version: '1.0',
  meta: {
    theme: 'tokyo-night',
    windowStyle: 'macos',
    dimensions: { width: 24, height: 4 },
    physics: 'human',
    seed: 42,
    title: 'demo',
  },
  events: [
    { type: 'prompt', text: '$ ' },
    { type: 'type', text: 'bun test', delay: 60 },
    { type: 'wait', duration: 300 },
    { type: 'output', text: '✔ 42 passed', color: '#9ece6a' },
  ],
})

describe('svg renderer', () => {
  it('is deterministic (byte-identical output)', () => {
    expect(renderSVG(hero)).toBe(renderSVG(hero))
  })

  it('escapes user text (injection-safe)', () => {
    const evil = parseTimeline({
      ...hero,
      events: [{ type: 'output', text: '<script>alert(1)</script>' }],
    })
    const svg = renderSVG(evil)
    expect(svg).not.toContain('<script>')
    expect(svg).toContain('&lt;')
    expect(svg).toContain('&gt;')
  })

  it('renders all four chrome styles', () => {
    for (const windowStyle of ['macos', 'flat', 'minimal', 'none'] as const) {
      const svg = renderSVG(parseTimeline({ ...hero, meta: { ...hero.meta, windowStyle } }))
      expect(svg.startsWith('<!-- generated by typeframe -->')).toBe(true)
      expect(svg.endsWith('</svg>')).toBe(true)
    }
  })

  it('includes the reduced-motion static fallback', () => {
    expect(renderSVG(hero)).toContain('prefers-reduced-motion')
  })

  it('stays within the 50KB budget for the example timeline', () => {
    expect(Buffer.byteLength(renderSVG(hero))).toBeLessThan(50 * 1024)
  })

  it('matches the golden snapshot', () => {
    expect(renderSVG(hero)).toMatchSnapshot()
  })
})
